# Generated by Django 2.2 on 2019-04-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190402_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preference',
            field=models.TextField(blank=True, max_length=32),
        ),
    ]
