# Generated by Django 2.2 on 2019-04-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='API_KEY',
            field=models.TextField(blank=True, max_length=32),
        ),
    ]
