# Generated by Django 2.2 on 2019-04-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_preference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='preference',
            new_name='topic',
        ),
    ]
